name: Pass Test
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    container: strikef/swpp-ci:latest


    steps:
      - name: alive2 clone
        run: |
          ln -s /opt/llvm ~/llvm-swpp
          
      - uses: actions/cache@v3
        id: alive_cache
        name: check cache alive2
        with:
          path: ${{ github.workspace }}/alive2
          key: ${{ runner.os }}-alive
          
      # need build
      - if: steps.alive_cache.outputs.cache-hit != 'true'
        name: build alive2
        run: |
          git clone https://github.com/AliveToolkit/alive2.git
          cd $GITHUB_WORKSPACE/alive2
          git checkout 9ca7092c21e69b4e71c91b9280cff920234410dc
          cmake -GNinja -Bbuild -DBUILD_TV=ON -DCMAKE_PREFIX_PATH="~/llvm-swpp;/opt/z3" -DCMAKE_BUILD_TYPE=Release -DZ3_INCLUDE_DIR=/opt/z3/include -DZ3_LIBRARIES=/opt/z3/lib64/libz3.so
          cmake --build build
      # patch alive2
      - if: steps.alive_cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        name: get swpp repo
        with:
          repository: snu-sf-class/swpp202301
          path: ${{ github.workspace }}/swpp
          ref: main
      - if: steps.alive_cache.outputs.cache-hit != 'true'
        name: patch alive2
        run: |
          cd $GITHUB_WORKSPACE/alive2
          git apply ../swpp/project/alive2-swpp-intrinsics.patch
          ./build.sh
      - uses: actions/checkout@v3
        name: get compiler repo
        with:
          path: ${{ github.workspace }}/compiler
      # need build
      - name: build compiler
        run: |
          cd $GITHUB_WORKSPACE/compiler
          cmake -GNinja -Bbuild
          cmake --build build --target swpp-compiler
      - uses: actions/cache@v3
        name: check cache interpreter
        id: interpreter_cache
        with:
          path: ${{ github.workspace }}/interpreter-swpp
          key: ${{ runner.os }}-interpreter
      # need build
      - if: steps.interpreter_cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        name: get interpreter repo
        with:
          repository: snu-sf-class/swpp202301-interpreter
          path: ${{ github.workspace }}/interpreter-swpp
          ref: main
      - if: steps.interpreter_cache.outputs.cache-hit != 'true'
        name: build interpreter
        run: |
          cd $GITHUB_WORKSPACE/interpreter-swpp
          ./build.sh
          
      - name: test
        run: |
          cp -r $GITHUB_WORKSPACE/interpreter-swpp ~/
          cp -r $GITHUB_WORKSPACE/alive2 ~/
          cd $GITHUB_WORKSPACE/compiler/build
          ctest --output-on-failure
